branches:
    only:
        - master

language: python

python:
    - 3.7
    - 3.8

install:
    - pip install -r requirements.txt
    - pip install -r dev_requirements.txt

cache:
    - pip: true

script:
    - python setup.py install --prefix=$PYHOME
    - cd tests
    - nosetests test*.py --with-coverage --cover-package=fpfs --with-doctest --cover-erase

# after_success:
#     - codecov
